### ISSUE TITLE
Design Login Page UI Mockup

### ISSUE THREAD

**Issue by jeff-yc-wong** [RNDVOUZ/rndvouz-mobile-app#2]
![image](https://github.com/RNDVOUZ/rndvouz-mobile-app/assets/42687471/9dd27af3-dd4d-4d37-9129-59d0275fab5e)

**Comment by Sanyam-jain30** [comment]
Hey, I have expertise in it, can I please be assigned to it?

**Comment by FeimeiChen** [comment]
> I have experience in working on Flutter apps, can you please assign it to me?
Hello,
This is our student project, so we can't assign it to you. Sorry, but if you're interested in this project, you can read our code and give us any valuable suggestions.
Thanks,
Feimei Chen

**Comment by FeimeiChen** [comment]
> I have experience in working on Flutter apps, can you please assign it to me?

Hello,
This is our student project, so we can't assign it to you. Sorry, but if you're interested in this project, you can read our code and give us any valuable suggestions.
Thanks,
Feimei Chen
