### ISSUE TITLE
Create a widget for bottom navigation menu

### ISSUE THREAD

**Issue by jeff-yc-wong** [rndvouz/rndvouz-mobile-app#4]
![image](https://github.com/RNDVOUZ/rndvouz-mobile-app/assets/42687471/0f9d8047-b83c-4f94-a13f-d822850af22c)

- [ ] Home button
- [ ] Search button
- [ ] Upload Item Button
- [ ] Notification Button
- [ ] Profile Button

**Comment by Sanyam-jain30** [comment]
Hey, I have expertise in this, can I please be assigned to it?
